/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class connect_NativeClient */

#ifndef _Included_connect_NativeClient
#define _Included_connect_NativeClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     connect_NativeClient
 * Method:    connect
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_connect_NativeClient_connect
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     connect_NativeClient
 * Method:    track
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_connect_NativeClient_track
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     connect_NativeClient
 * Method:    stopTrack
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_connect_NativeClient_stopTrack
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     connect_NativeClient
 * Method:    getData
 * Signature: ([Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_connect_NativeClient_getData
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
