/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class connect_NativeServer */

#ifndef _Included_connect_NativeServer
#define _Included_connect_NativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     connect_NativeServer
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_connect_NativeServer_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
