/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class connect_NativeClient */

#ifndef _Included_connect_NativeClient
#define _Included_connect_NativeClient
#ifdef __cplusplus
extern "C" {
#endif
#undef connect_NativeClient_MIN_PRIORITY
#define connect_NativeClient_MIN_PRIORITY 1L
#undef connect_NativeClient_NORM_PRIORITY
#define connect_NativeClient_NORM_PRIORITY 5L
#undef connect_NativeClient_MAX_PRIORITY
#define connect_NativeClient_MAX_PRIORITY 10L
/*
 * Class:     connect_NativeClient
 * Method:    connect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_connect_NativeClient_connect
  (JNIEnv *, jobject);

/*
 * Class:     connect_NativeClient
 * Method:    track
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_connect_NativeClient_track
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
